#!/bin/bash

function usage() {
  echo "$0 [old_id] [new_id]"
  exit 0
}

if [[ -z "$1" ]]; then
  usage
fi
OLD_ID="$1"

if [[ -z "$2" ]]; then
  usage
fi
NEW_ID="$2"


declare -A ids
pushd fish-by-rarity2

for file in *; do
  echo "Loading $file..."
  while IFS= read -r line; do
    id="${line%% *}"
    rest="${line#* }"
    ids["$id"]="$rest"
  done < "$file"
done

popd

NEW_FISH="${ids["$NEW_ID"]}"
OLD_FISH="${ids["$OLD_ID"],,}"

echo "REPLACING $OLD_FISH WITH $NEW_FISH"

pushd badcop_
find -type f | xargs sed -i 's/^'$OLD_ID',[^,]*,/'$NEW_ID','"$NEW_FISH"',/'
popd

# delete the old type of fish from existence
pushd fish-by-rarity2
sed -i '/'$OLD_ID' /d' *;
popd

# delete the image
cd ~/twitch-overlay/public/fish
rm "$OLD_FISH.png"
