#!/bin/bash

declare -A USERNAME_CACHE
declare -A USERID_CACHE
function load_cache() {
  local USER_ID
  local USER_NAME
  while read -r USER_ID USER_NAME; do
    USERNAME_CACHE[$USER_ID]=$USER_NAME
    USERID_CACHE[${USER_NAME,,}]=$USER_ID
  done < data/username_cache
}
load_cache

JSON=badcop_/hall-of-fame/json

while IFS= read -r line; do
  CAUGHT_BY="$(echo "$line" | jq -r .caughtBy)"
  ID="${USERID_CACHE[${CAUGHT_BY,,}]}"
  if [[ -z "$ID" ]]; then
    echo "$line"
  else
    jq -cr '.twitchID='$ID <<< "$line"
  fi
done < $JSON
