#!/bin/bash
source ~/copfish/secrets.sh

FISH_ROOT=~/fishing-data

urlencode() {
    # Usage: urlencode "string"
    local LC_ALL=C
    for (( i = 0; i < ${#1}; i++ )); do
        : "${1:i:1}"
        case "$_" in
            [a-zA-Z0-9.~_-])
                printf '%s' "$_"
            ;;

            *)
                printf '%%%02X' "'$_"
            ;;
        esac
    done
    printf '\n'
}

TOKEN="$(curl -Ss -X POST https://id.twitch.tv/oauth2/token \
  -d "client_id=$TWITCH_CLIENT_ID" \
  -d "client_secret=$TWITCH_CLIENT_SECRET" \
  -d "grant_type=client_credentials" \
  | jq -r '.access_token')"

function migrate() {
  jq -c --unbuffered | while IFS= read -r line; do
    CHUNK="$(echo "$line" | jq -rc '.data | .[]')"
    while IFS= read line2; do
      ID="$(echo "$line2" | jq -r '.id')"
      NAME="$(echo "$line2" | jq -r '.display_name')"
      if [[ ! -z "$ID" ]]; then
        echo "$ID $NAME" >> data/username_cache
      else
        echo "NOT FOUND"
      fi
    done <<< "$CHUNK"
  done
}

cat fark | xargs -n 1 echo \
  | sed 's/ /\&id=/g;s@^@https://api.twitch.tv/helix/users?id=@' \
  | xargs -P1 -L1 curl -Ss \
  -H "Authorization: Bearer $TOKEN" \
  -H "Client-Id: $TWITCH_CLIENT_ID" \
  | migrate
