#!/bin/bash

cd fish-by-rarity2

ID=5000
while IFS= read -r file; do 
  while IFS= read -r fish; do
    fish="${fish#* }"
    echo "$ID $fish"
    ((ID++))
  done < "$file" > >(sponge "${file}")
done < <(find -type f)


